export const Action = {
  START: 'start',
  STOP: 'stop',
  RESTART: 'restart',
  STATUS: 'status',
  INSTALL: 'install',
  ADOPT: 'adopt',
  UPDATE: 'update',
  BACKUP: 'backup',
  RESTORE: 'restore',
  LOGS: 'logs',
  DOCTOR: 'doctor',
  KICK: 'kick',
  BAN: 'ban',
  MOVE: 'move',
  POKE: 'poke',
  CHANNEL_CREATE: 'channel.create',
  CHANNEL_EDIT: 'channel.edit',
  CHANNEL_DELETE: 'channel.delete',
  CHANNEL_MOVE: 'channel.move',
  SERVER_CONFIG_READ: 'server.config.read',
  SERVER_CONFIG_WRITE: 'server.config.write',
  API_ENABLE: 'api.enable',
  API_DISABLE: 'api.disable',
  API_STATUS: 'api.status',
  PAIR: 'pair',
  UNPAIR: 'unpair',
  ROTATE_SECRET: 'rotate-secret',
} as const;

export type ActionValue = (typeof Action)[keyof typeof Action];
