import { AppError, ErrorCode } from '../domain/errors.ts';
import { dirname } from 'node:path';

export interface ServerUnitOptions {
  user: string;
  group: string;
  installPath: string;
  startScript?: string;
}

export interface AgentUnitOptions {
  user: string;
  group: string;
  execStart: string;
  configPath: string;
  installPath: string;
  dataDir?: string;
}

const HARDENING_COMMON = `NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=read-only
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
RestrictRealtime=true
LockPersonality=true
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
`;

// Native TS3 server binary: keep W^X hardening. Node.js/V8 requires executable
// memory for its JIT, so MemoryDenyWriteExecute is intentionally NOT applied to
// the agent unit.
const HARDENING_SERVER = `${HARDENING_COMMON}MemoryDenyWriteExecute=true
`;

export function validateUnitName(name: string): boolean {
  return /^[a-zA-Z0-9_.-]+$/.test(name) && name.length <= 64;
}

function validateIdentity(value: string): void {
  if (!/^[a-z_][a-z0-9_-]*[$]?$/i.test(value)) {
    throw new AppError(ErrorCode.VALIDATION, 'Invalid systemd user or group');
  }
}

function validatePath(value: string): void {
  // Restrict paths to literal absolute paths: systemd expands % specifiers and
  // whitespace separates arguments. Reject them rather than emit unsafe units.
  if (!value.startsWith('/') || /[\s\0%"'\\]/.test(value) || value.split('/').includes('..')) {
    throw new AppError(ErrorCode.VALIDATION, `Expected a literal absolute systemd path: ${value}`);
  }
}

export function generateServerUnit(options: ServerUnitOptions): string {
  if (options.user.length === 0 || options.group.length === 0 || options.installPath.length === 0) {
    throw new AppError(ErrorCode.VALIDATION, 'user, group and installPath are required');
  }
  const startScript = options.startScript ?? 'ts3server_startscript.sh';
  validateIdentity(options.user);
  validateIdentity(options.group);
  validatePath(options.installPath);
  if (!/^[a-zA-Z0-9_.-]+$/.test(startScript)) {
    throw new AppError(ErrorCode.VALIDATION, 'startScript must be a filename');
  }
  return `# Generated by ts3-manager systemd generate ts3server
# Runtime requirements:
#   - ${options.installPath} must be owned by ${options.user}:${options.group}
#   - ${options.installPath}/files, logs and ts3server.sqlitedb must be writable
#     by the service user (ReadWritePaths below).
#   - The official start script daemonizes the server (Type=forking).

[Unit]
Description=TeamSpeak 3 Server (managed by TS3 Community Operations)
After=network.target

[Service]
Type=forking
User=${options.user}
Group=${options.group}
WorkingDirectory=${options.installPath}
ExecStart=${options.installPath}/${startScript} start
ExecStop=${options.installPath}/${startScript} stop
ExecReload=${options.installPath}/${startScript} restart
Restart=on-failure
RestartSec=5
ReadWritePaths=${options.installPath}

${HARDENING_SERVER}
[Install]
WantedBy=multi-user.target
`;
}

export function generateAgentUnit(options: AgentUnitOptions): string {
  if (options.user.length === 0 || options.group.length === 0 || options.execStart.length === 0 || options.configPath.length === 0) {
    throw new AppError(ErrorCode.VALIDATION, 'user, group, execStart and configPath are required');
  }
  validateIdentity(options.user);
  validateIdentity(options.group);
  validatePath(options.configPath);
  if (!options.execStart.startsWith('/') || /[\r\n\0%]/.test(options.execStart)) {
    throw new AppError(ErrorCode.VALIDATION, 'execStart must use an absolute executable path without systemd specifiers');
  }
  const writable = new Set([dirname(options.configPath)]);
  if (options.dataDir) writable.add(options.dataDir);
  if (options.installPath) writable.add(options.installPath);
  for (const path of writable) validatePath(path);
  return `# Generated by ts3-manager systemd generate ts3-agent
# Runtime requirements:
#   - The agent runs as the unprivileged user ${options.user}:${options.group}.
#   - ${options.configPath} (config file) must be readable/writable by that user.
#   - If identity verification is enabled, the TS3 install path must be readable
#     and the agent must be able to open a ServerQuery connection.
#   - NOTE: MemoryDenyWriteExecute is intentionally NOT set: Node.js/V8 requires
#     JIT executable memory and would crash under W^X.

[Unit]
Description=TS3 Community Operations Agent (Host Control Plane)
After=network.target

[Service]
Type=simple
User=${options.user}
Group=${options.group}
ExecStart=${options.execStart}
Environment=TS3_MANAGER_CONFIG=${options.configPath}
Restart=on-failure
RestartSec=5
ReadWritePaths=${[...writable].join(' ')}
UMask=0077

${HARDENING_COMMON}
[Install]
WantedBy=multi-user.target
`;
}
